version: '2'
services:
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      DB_HOST: "db"
  web:
    build: .
    volumes:
      - .:/myapp
    ports:
      - "80:80"
    depends_on:
      - db
